name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        docker build -t familiar .
        docker run -rm familiar
