name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
       
      - name: Docker setup
        uses: docker-practice/actions-setup-docker@master
        
      - name: Build and run
        run: |
              docker build -t familiar .
              docker run --rm familiar
