name: 'Build'

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        docker run -rm familiar
